MVCTestProject/MVCTestProject/Controllers/SendDataFromViewToActionController.cs
using MVCTestProject.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace MVCTestProject.Controllers
{
    public class SendDataFromViewToActionController : Controller
    {
        // GET: SendDataFromViewToAction
        public ActionResult SimpleInterest()
        {
            return View();
        }

        #region Using Traditional Approach
        ////By default POST request comes here
        //public ActionResult CalculateSimpleInterestResult()
        //{
        //    decimal principle = Convert.ToDecimal(Request["txtAmount"].ToString());
        //    decimal rate = Convert.ToDecimal(Request["txtRate"].ToString());
        //    int time = Convert.ToInt32(Request["txtYear"].ToString());

        //    decimal simpleInteresrt = (principle * time * rate) / 100;

        //    StringBuilder sbInterest = new StringBuilder();
        //    sbInterest.Append("<b>Amount :</b> " + principle + "<br/>");
        //    sbInterest.Append("<b>Rate :</b> " + rate + "<br/>");
        //    sbInterest.Append("<b>Time(year) :</b> " + time + "<br/>");
        //    sbInterest.Append("<b>Interest :</b> " + simpleInteresrt);
        //    return Content(sbInterest.ToString());
        //}
        #endregion

        #region Using FormCollection

        //public ActionResult CalculateSimpleInterestResult(FormCollection form)
        //{
        //    decimal principle = Convert.ToDecimal(form["txtAmount"].ToString());
        //    decimal rate = Convert.ToDecimal(form["txtRate"].ToString());
        //    int time = Convert.ToInt32(form["txtYear"].ToString());

        //    decimal simpleInteresrt = (principle * time * rate) / 100;

        //    StringBuilder sbInterest = new StringBuilder();
        //    sbInterest.Append("<b>Amount :</b> " + principle + "<br/>");
        //    sbInterest.Append("<b>Rate :</b> " + rate + "<br/>");
        //    sbInterest.Append("<b>Time(year) :</b> " + time + "<br/>");
        //    sbInterest.Append("<b>Interest :</b> " + simpleInteresrt);
        //    return Content(sbInterest.ToString());
        //}
        #endregion

        #region Using Parameters
        //[HttpPost]
        //public ActionResult CalculateSimpleInterestResult(string txtAmount, string txtRate, string txtYear)
        //{
        //    decimal principle = Convert.ToDecimal(txtAmount);
        //    decimal rate = Convert.ToDecimal(txtRate);
        //    int time = Convert.ToInt32(txtYear);

        //    decimal simpleInteresrt = (principle * time * rate) / 100;

        //    StringBuilder sbInterest = new StringBuilder();
        //    sbInterest.Append("<b>Amount :</b> " + principle + "<br/>");
        //    sbInterest.Append("<b>Rate :</b> " + rate + "<br/>");
        //    sbInterest.Append("<b>Time(year) :</b> " + time + "<br/>");
        //    sbInterest.Append("<b>Interest :</b> " + simpleInteresrt);
        //    return Content(sbInterest.ToString());
        //}
        #endregion

        public ActionResult SimpleInterestWithModel()
        {
            SimpleInterestModel model = new SimpleInterestModel();
            return View(model);
        }

        [HttpPost]
        [HandleError]
        public ContentResult CalculateSimpleInterestResult(SimpleInterestModel model)
        {
            Session["Name"] = "Helo";
            HttpContext.Session["jj"] = "lkl";
            decimal simpleInteresrt = (model.Amount * model.Year * model.Rate) / 100;
            StringBuilder sbInterest = new StringBuilder();
            sbInterest.Append("<b>Amount :</b> " + model.Amount + "<br/>");
            sbInterest.Append("<b>Rate :</b> " + model.Rate + "<br/>");
            sbInterest.Append("<b>Time(year) :</b> " + model.Year + "<br/>");
            sbInterest.Append("<b>Interest :</b> " + simpleInteresrt);
            return Content(sbInterest.ToString());
        }
    }
}

MVCTestProject/MVCTestProject/Views/SendDataFromViewToAction/SimpleInterest.cshtml
@{
    ViewBag.Title = "SimpleInterest";
}

<fieldset>
    <legend>Calculate Simple Interest</legend>
    @using (Ajax.BeginForm("CalculateSimpleInterestResult", "SendDataFromViewToAction",
                            new AjaxOptions { UpdateTargetId = "divInterestDeatils" }))
    {
        <div id="divInterestDeatils"></div>
        <ol>
            <li>
                @Html.Label("Amount")
                @Html.TextBox("txtAmount")
            </li>
            <li>
                @Html.Label("Rate")
                @Html.TextBox("txtRate")
            </li>
            <li>
                @Html.Label("Year")
                @Html.TextBox("txtYear")
            </li>
        </ol>
        <button>Calculate</button>
    }
</fieldset> 

MVCTestProject/MVCTestProject/Views/SendDataFromViewToAction/SimpleInterestWithModel.cshtml
@model MVCTestProject.Models.SimpleInterestModel
@{
    ViewBag.Title = "SimpleInterestWithModel";
}

@using (Ajax.BeginForm("CalculateSimpleInterestResult", "SendDataFromViewToAction",
                            new AjaxOptions { UpdateTargetId = "divInterestDeatils" }))
{

    <fieldset>
        <legend>Calulate Simple Interest</legend>
        <div id="divInterestDeatils"></div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Amount)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Amount)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Rate)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Rate)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Year)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Year)
        </div>
        <p>
            <input type="submit" value="Calculate" />
        </p>
    </fieldset>
}